fix(4allportal): create samba user with correct uid (#320)
* fix: create samba users with correct uids

* chore: Update 'README.md's

---------

Co-authored-by: C-schwarz-4ap <C-schwarz-4ap@users.noreply.github.com>

diff --git a/charts/4allportal/templates/samba/deployment.yaml b/charts/4allportal/templates/samba/deployment.yaml
--- a/charts/4allportal/templates/samba/deployment.yaml
+++ b/charts/4allportal/templates/samba/deployment.yaml
@@ -34,6 +34,20 @@ spec:
           args:
             - |
               useradd -u 1000 4allportal
+              USER_FILE="/etc/container-users/users.json"
+              if [ ! -f "$USER_FILE" ]; then
+                  echo "Error: JSON file not found at $USER_FILE"
+                  exit 1
+              fi
+              usernames=$(grep -oP '"name"\s*:\s*"\K[^"]+' "$USER_FILE")
+              for username in $usernames; do
+                  if id "$username" &>/dev/null; then
+                      echo "User $username already exists. Skipping."
+                  else
+                      useradd -m "$username"
+                      echo "User $username created."
+                  fi
+              done
               samba-container run smbd
           volumeMounts:
             - mountPath: /etc/container-config
